services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: web
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./data:/app/data
