services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./apps/backend/data:/app/data
