/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as AuthVerifyIndexRouteImport } from './routes/_auth/verify/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as DashboardSettingsUsersRouteRouteImport } from './routes/_dashboard/settings/users/route'
import { Route as DashboardSettingsRolesRouteRouteImport } from './routes/_dashboard/settings/roles/route'
import { Route as DashboardSettingsNotificationsRouteRouteImport } from './routes/_dashboard/settings/notifications/route'
import { Route as DashboardSettingsUsersIndexRouteImport } from './routes/_dashboard/settings/users/index'
import { Route as DashboardSettingsRolesIndexRouteImport } from './routes/_dashboard/settings/roles/index'
import { Route as DashboardSettingsNotificationsIndexRouteImport } from './routes/_dashboard/settings/notifications/index'
import { Route as DashboardSettingsRolesNameRouteRouteImport } from './routes/_dashboard/settings/roles/$name/route'
import { Route as DashboardSettingsUsersUserIdIndexRouteImport } from './routes/_dashboard/settings/users/$userId/index'
import { Route as DashboardSettingsRolesNamePermissionsIndexRouteImport } from './routes/_dashboard/settings/roles/$name/permissions/index'
import { Route as DashboardSettingsRolesNameMembersIndexRouteImport } from './routes/_dashboard/settings/roles/$name/members/index'
import { Route as DashboardSettingsRolesNameDisplayIndexRouteImport } from './routes/_dashboard/settings/roles/$name/_display/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthVerifyIndexRoute = AuthVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardSettingsUsersRouteRoute =
  DashboardSettingsUsersRouteRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsRolesRouteRoute =
  DashboardSettingsRolesRouteRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsNotificationsRouteRoute =
  DashboardSettingsNotificationsRouteRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsUsersIndexRoute =
  DashboardSettingsUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSettingsUsersRouteRoute,
  } as any)
const DashboardSettingsRolesIndexRoute =
  DashboardSettingsRolesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSettingsRolesRouteRoute,
  } as any)
const DashboardSettingsNotificationsIndexRoute =
  DashboardSettingsNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSettingsNotificationsRouteRoute,
  } as any)
const DashboardSettingsRolesNameRouteRoute =
  DashboardSettingsRolesNameRouteRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => DashboardSettingsRolesRouteRoute,
  } as any)
const DashboardSettingsUsersUserIdIndexRoute =
  DashboardSettingsUsersUserIdIndexRouteImport.update({
    id: '/$userId/',
    path: '/$userId/',
    getParentRoute: () => DashboardSettingsUsersRouteRoute,
  } as any)
const DashboardSettingsRolesNamePermissionsIndexRoute =
  DashboardSettingsRolesNamePermissionsIndexRouteImport.update({
    id: '/permissions/',
    path: '/permissions/',
    getParentRoute: () => DashboardSettingsRolesNameRouteRoute,
  } as any)
const DashboardSettingsRolesNameMembersIndexRoute =
  DashboardSettingsRolesNameMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => DashboardSettingsRolesNameRouteRoute,
  } as any)
const DashboardSettingsRolesNameDisplayIndexRoute =
  DashboardSettingsRolesNameDisplayIndexRouteImport.update({
    id: '/_display/',
    path: '/',
    getParentRoute: () => DashboardSettingsRolesNameRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/profile': typeof DashboardProfileRoute
  '/': typeof DashboardIndexRoute
  '/settings/notifications': typeof DashboardSettingsNotificationsRouteRouteWithChildren
  '/settings/roles': typeof DashboardSettingsRolesRouteRouteWithChildren
  '/settings/users': typeof DashboardSettingsUsersRouteRouteWithChildren
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/verify': typeof AuthVerifyIndexRoute
  '/settings/roles/$name': typeof DashboardSettingsRolesNameRouteRouteWithChildren
  '/settings/notifications/': typeof DashboardSettingsNotificationsIndexRoute
  '/settings/roles/': typeof DashboardSettingsRolesIndexRoute
  '/settings/users/': typeof DashboardSettingsUsersIndexRoute
  '/settings/users/$userId': typeof DashboardSettingsUsersUserIdIndexRoute
  '/settings/roles/$name/': typeof DashboardSettingsRolesNameDisplayIndexRoute
  '/settings/roles/$name/members': typeof DashboardSettingsRolesNameMembersIndexRoute
  '/settings/roles/$name/permissions': typeof DashboardSettingsRolesNamePermissionsIndexRoute
}
export interface FileRoutesByTo {
  '/profile': typeof DashboardProfileRoute
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/verify': typeof AuthVerifyIndexRoute
  '/settings/notifications': typeof DashboardSettingsNotificationsIndexRoute
  '/settings/roles': typeof DashboardSettingsRolesIndexRoute
  '/settings/users': typeof DashboardSettingsUsersIndexRoute
  '/settings/users/$userId': typeof DashboardSettingsUsersUserIdIndexRoute
  '/settings/roles/$name': typeof DashboardSettingsRolesNameDisplayIndexRoute
  '/settings/roles/$name/members': typeof DashboardSettingsRolesNameMembersIndexRoute
  '/settings/roles/$name/permissions': typeof DashboardSettingsRolesNamePermissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/settings/notifications': typeof DashboardSettingsNotificationsRouteRouteWithChildren
  '/_dashboard/settings/roles': typeof DashboardSettingsRolesRouteRouteWithChildren
  '/_dashboard/settings/users': typeof DashboardSettingsUsersRouteRouteWithChildren
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_auth/verify/': typeof AuthVerifyIndexRoute
  '/_dashboard/settings/roles/$name': typeof DashboardSettingsRolesNameRouteRouteWithChildren
  '/_dashboard/settings/notifications/': typeof DashboardSettingsNotificationsIndexRoute
  '/_dashboard/settings/roles/': typeof DashboardSettingsRolesIndexRoute
  '/_dashboard/settings/users/': typeof DashboardSettingsUsersIndexRoute
  '/_dashboard/settings/users/$userId/': typeof DashboardSettingsUsersUserIdIndexRoute
  '/_dashboard/settings/roles/$name/_display/': typeof DashboardSettingsRolesNameDisplayIndexRoute
  '/_dashboard/settings/roles/$name/members/': typeof DashboardSettingsRolesNameMembersIndexRoute
  '/_dashboard/settings/roles/$name/permissions/': typeof DashboardSettingsRolesNamePermissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile'
    | '/'
    | '/settings/notifications'
    | '/settings/roles'
    | '/settings/users'
    | '/login'
    | '/register'
    | '/verify'
    | '/settings/roles/$name'
    | '/settings/notifications/'
    | '/settings/roles/'
    | '/settings/users/'
    | '/settings/users/$userId'
    | '/settings/roles/$name/'
    | '/settings/roles/$name/members'
    | '/settings/roles/$name/permissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/profile'
    | '/'
    | '/login'
    | '/register'
    | '/verify'
    | '/settings/notifications'
    | '/settings/roles'
    | '/settings/users'
    | '/settings/users/$userId'
    | '/settings/roles/$name'
    | '/settings/roles/$name/members'
    | '/settings/roles/$name/permissions'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_dashboard/profile'
    | '/_dashboard/'
    | '/_dashboard/settings/notifications'
    | '/_dashboard/settings/roles'
    | '/_dashboard/settings/users'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_auth/verify/'
    | '/_dashboard/settings/roles/$name'
    | '/_dashboard/settings/notifications/'
    | '/_dashboard/settings/roles/'
    | '/_dashboard/settings/users/'
    | '/_dashboard/settings/users/$userId/'
    | '/_dashboard/settings/roles/$name/_display/'
    | '/_dashboard/settings/roles/$name/members/'
    | '/_dashboard/settings/roles/$name/permissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/verify/': {
      id: '/_auth/verify/'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dashboard/settings/users': {
      id: '/_dashboard/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof DashboardSettingsUsersRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings/roles': {
      id: '/_dashboard/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof DashboardSettingsRolesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings/notifications': {
      id: '/_dashboard/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings/users/': {
      id: '/_dashboard/settings/users/'
      path: '/'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof DashboardSettingsUsersIndexRouteImport
      parentRoute: typeof DashboardSettingsUsersRouteRoute
    }
    '/_dashboard/settings/roles/': {
      id: '/_dashboard/settings/roles/'
      path: '/'
      fullPath: '/settings/roles/'
      preLoaderRoute: typeof DashboardSettingsRolesIndexRouteImport
      parentRoute: typeof DashboardSettingsRolesRouteRoute
    }
    '/_dashboard/settings/notifications/': {
      id: '/_dashboard/settings/notifications/'
      path: '/'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof DashboardSettingsNotificationsIndexRouteImport
      parentRoute: typeof DashboardSettingsNotificationsRouteRoute
    }
    '/_dashboard/settings/roles/$name': {
      id: '/_dashboard/settings/roles/$name'
      path: '/$name'
      fullPath: '/settings/roles/$name'
      preLoaderRoute: typeof DashboardSettingsRolesNameRouteRouteImport
      parentRoute: typeof DashboardSettingsRolesRouteRoute
    }
    '/_dashboard/settings/users/$userId/': {
      id: '/_dashboard/settings/users/$userId/'
      path: '/$userId'
      fullPath: '/settings/users/$userId'
      preLoaderRoute: typeof DashboardSettingsUsersUserIdIndexRouteImport
      parentRoute: typeof DashboardSettingsUsersRouteRoute
    }
    '/_dashboard/settings/roles/$name/permissions/': {
      id: '/_dashboard/settings/roles/$name/permissions/'
      path: '/permissions'
      fullPath: '/settings/roles/$name/permissions'
      preLoaderRoute: typeof DashboardSettingsRolesNamePermissionsIndexRouteImport
      parentRoute: typeof DashboardSettingsRolesNameRouteRoute
    }
    '/_dashboard/settings/roles/$name/members/': {
      id: '/_dashboard/settings/roles/$name/members/'
      path: '/members'
      fullPath: '/settings/roles/$name/members'
      preLoaderRoute: typeof DashboardSettingsRolesNameMembersIndexRouteImport
      parentRoute: typeof DashboardSettingsRolesNameRouteRoute
    }
    '/_dashboard/settings/roles/$name/_display/': {
      id: '/_dashboard/settings/roles/$name/_display/'
      path: '/'
      fullPath: '/settings/roles/$name/'
      preLoaderRoute: typeof DashboardSettingsRolesNameDisplayIndexRouteImport
      parentRoute: typeof DashboardSettingsRolesNameRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthVerifyIndexRoute: typeof AuthVerifyIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthVerifyIndexRoute: AuthVerifyIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardSettingsNotificationsRouteRouteChildren {
  DashboardSettingsNotificationsIndexRoute: typeof DashboardSettingsNotificationsIndexRoute
}

const DashboardSettingsNotificationsRouteRouteChildren: DashboardSettingsNotificationsRouteRouteChildren =
  {
    DashboardSettingsNotificationsIndexRoute:
      DashboardSettingsNotificationsIndexRoute,
  }

const DashboardSettingsNotificationsRouteRouteWithChildren =
  DashboardSettingsNotificationsRouteRoute._addFileChildren(
    DashboardSettingsNotificationsRouteRouteChildren,
  )

interface DashboardSettingsRolesNameRouteRouteChildren {
  DashboardSettingsRolesNameDisplayIndexRoute: typeof DashboardSettingsRolesNameDisplayIndexRoute
  DashboardSettingsRolesNameMembersIndexRoute: typeof DashboardSettingsRolesNameMembersIndexRoute
  DashboardSettingsRolesNamePermissionsIndexRoute: typeof DashboardSettingsRolesNamePermissionsIndexRoute
}

const DashboardSettingsRolesNameRouteRouteChildren: DashboardSettingsRolesNameRouteRouteChildren =
  {
    DashboardSettingsRolesNameDisplayIndexRoute:
      DashboardSettingsRolesNameDisplayIndexRoute,
    DashboardSettingsRolesNameMembersIndexRoute:
      DashboardSettingsRolesNameMembersIndexRoute,
    DashboardSettingsRolesNamePermissionsIndexRoute:
      DashboardSettingsRolesNamePermissionsIndexRoute,
  }

const DashboardSettingsRolesNameRouteRouteWithChildren =
  DashboardSettingsRolesNameRouteRoute._addFileChildren(
    DashboardSettingsRolesNameRouteRouteChildren,
  )

interface DashboardSettingsRolesRouteRouteChildren {
  DashboardSettingsRolesNameRouteRoute: typeof DashboardSettingsRolesNameRouteRouteWithChildren
  DashboardSettingsRolesIndexRoute: typeof DashboardSettingsRolesIndexRoute
}

const DashboardSettingsRolesRouteRouteChildren: DashboardSettingsRolesRouteRouteChildren =
  {
    DashboardSettingsRolesNameRouteRoute:
      DashboardSettingsRolesNameRouteRouteWithChildren,
    DashboardSettingsRolesIndexRoute: DashboardSettingsRolesIndexRoute,
  }

const DashboardSettingsRolesRouteRouteWithChildren =
  DashboardSettingsRolesRouteRoute._addFileChildren(
    DashboardSettingsRolesRouteRouteChildren,
  )

interface DashboardSettingsUsersRouteRouteChildren {
  DashboardSettingsUsersIndexRoute: typeof DashboardSettingsUsersIndexRoute
  DashboardSettingsUsersUserIdIndexRoute: typeof DashboardSettingsUsersUserIdIndexRoute
}

const DashboardSettingsUsersRouteRouteChildren: DashboardSettingsUsersRouteRouteChildren =
  {
    DashboardSettingsUsersIndexRoute: DashboardSettingsUsersIndexRoute,
    DashboardSettingsUsersUserIdIndexRoute:
      DashboardSettingsUsersUserIdIndexRoute,
  }

const DashboardSettingsUsersRouteRouteWithChildren =
  DashboardSettingsUsersRouteRoute._addFileChildren(
    DashboardSettingsUsersRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsNotificationsRouteRoute: typeof DashboardSettingsNotificationsRouteRouteWithChildren
  DashboardSettingsRolesRouteRoute: typeof DashboardSettingsRolesRouteRouteWithChildren
  DashboardSettingsUsersRouteRoute: typeof DashboardSettingsUsersRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsNotificationsRouteRoute:
    DashboardSettingsNotificationsRouteRouteWithChildren,
  DashboardSettingsRolesRouteRoute:
    DashboardSettingsRolesRouteRouteWithChildren,
  DashboardSettingsUsersRouteRoute:
    DashboardSettingsUsersRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
